config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :invoices
  resources :invoice_lines
  resources :firms
  resources :clients
  # match ':controller(/:action(/:id))(.:format)'

  root to: 'invoices#index'
end

app/models/invoice.rb
# frozen_string_literal: true

# Author: Walter Schreppers
# Description:
# Stores invoice in database, linked to client and firm,
# has many invoice lines and has nested attributes for invoice
# lines
class Invoice < ActiveRecord::Base
  belongs_to :client
  belongs_to :firm

  has_many :invoice_lines, dependent: :destroy
  accepts_nested_attributes_for :invoice_lines, reject_if: ->(f) { f[:description].blank? }, allow_destroy: true

  def mededeling
    FactuurMededeling.new(number).mededeling unless offerte
  end

  def title
    if offerte
      title =  'OFFERTE'
      title += ": #{id}" unless id.blank?
    else
      title = 'FACTUUR'
      title += ": #{number}" unless number.blank?
    end
    title
  end

  def firm_prefix
    firm.name.strip.tr(' ', '_')
  end

  def file_name
    if offerte
      "#{firm_prefix}_offerte_#{id}.pdf"
    else
      "#{firm_prefix}_factuur_#{number}.pdf"
    end
  end

  # def getnumber
  #   if offerte
  #     id.to_s
  #   else
  #     number.to_s
  #   end
  # end

  def generate_number(isofferte)
    return id if isofferte.to_i == 1

    # TODO: scope per firm here!
    last_invoice = Invoice.order('number').last

    self.number = if last_invoice
                    last_invoice.number + 1
                  else
                    # generate invoice nr based on year+month
                    "#{Time.new.strftime('%Y%m')}0001".to_i
                  end
  end

  def total_ex_vat
    total = 0.0
    invoice_lines.each do |item|
      total += item.total unless item.total.blank?
    end
    total
  end

  def vat
    (total_ex_vat * 0.21).round(2)
  end

  def total
    (total_ex_vat + vat).round(2)
  end

  def to_euro(amount)
    number_to_currency(amount, unit: '&euro; ').to_s
  end
end

app/controllers/invoices_controller.rb
# frozen_string_literal: true

# Author: Walter Schreppers
# Description:
#   Invoices handles both invoices and proforma invoices (offertes).
#   uses nested resource invoice_lines.
#
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[show edit update destroy]

  prawnto prawn: { page_size: 'A4', page_layout: :portrait }, inline: false

  def index
    if params[:q].blank?
      @invoices = Invoice.includes(:client).includes(:invoice_lines).order('number DESC').all
    else
      search = params[:q]
      @invoices = Invoice.includes(:client).includes(:invoice_lines)
                         .joins(:client).joins(:invoice_lines)
                         .where(
                           'number LIKE ? or invoice_lines.description LIKE ? or clients.name LIKE ?',
                           "%#{search}%", "%#{search}%", "%#{search}%"
                         ).order('number DESC').all
    end
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = InvoicePdf.new(@invoice)
        send_data pdf.render, filename: @invoice.file_name.to_s,
                              type: 'application/pdf',
                              disposition: 'attachment'
      end
    end
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = "Factuur met id=#{params[:id]} niet gevonden!"
    redirect_to action: 'index'
  end

  def search
    @invoice = Invoice.find_by_number(params[:id])

    if @invoice.blank?
      flash[:notice] = "Factuur #{params[:id]} niet gevonden!"
    else
      flash[:notice] = 'Factuur gevonden'
      redirect_to action: 'show', id: @invoice.id
    end
  end

  def new
    @invoice = Invoice.new
    @invoice.invoice_lines.build
    # @invoice.firm = Firm.first
    @invoice.offerte = true

    @invoice.datum = Date.today
  end

  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.generate_number(invoice_params[:offerte])

    if @invoice.save
      flash[:notice] = 'Successfully created invoice.'
      redirect_to @invoice
    else
      render action: 'new'
    end
  end

  def edit; end

  def update
    @invoice.generate_number(invoice_params[:offerte])

    if @invoice.update_attributes(invoice_params)
      flash[:notice] = 'Successfully updated invoice.'
      redirect_to @invoice
    else
      render action: 'edit'
    end
  end

  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy
    flash[:notice] = 'Successfully destroyed invoice.'
    redirect_to invoices_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def invoice_params
    params.require(:invoice).permit(:number, :datum, :client_id,
                                    :firm_id, :offerte, :no_vat,
                                    invoice_lines_attributes:
                                      %i[id description qty price _destroy])
  end
end

app/views/invoices/_form.html.erb
<%= simple_form_for invoice do |f| %>
  
    <%= render "layouts/error_messages", :target => invoice %>
    
    <% if !invoice.offerte %>
      <%= f.input :number, :label=>'Factuur NR', :input_html => { :maxlength=>10 } %>
    <% end %>

    <%= f.input :datum, :label=>'Datum van opmaak' %>

   
    <%= f.association :firm, selected: Firm.first.id %>
    <%= f.association :client, collection: Client.order('created_at DESC'), label: 'Kies klant', include_blank: false %>
    
    
    <div class="largecheckbox2">
      <%#= f.input :offerte, :label=>'Offerte', :as=>:select, o %>
      <%= f.collection_select :offerte, [[true, 'OFFERTE'] ,[false, 'FACTUUR']], :first, :last %>
    </div>

    <%= f.input :no_vat, :label=>"Outside belgium NO VAT" %>


  <div class="numeric required">
    <%= f.fields_for :invoice_lines do |builder| %>
      <%= render 'invoice_line_fields', :f => builder %>                  
    <% end %>
    <br/>
    <p><%= link_to_add_fields "Beschrijving toevoegen", f, :invoice_lines %></p> 
  </div>                                                                

   
    <%= f.submit 'Bewaren', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                invoices_path, :class => 'btn' %>
 
<% end %>

<br/>
<br/>

app/views/invoices/_invoice_line_fields.html.erb
<div class="fields">
  <table class="field_table">
  <tr>
    <td width="400px">
    <%= f.label :description, "Beschrijving" %>
    <%= f.text_area :description, :size=>"80x5", :class=>'wide_edit' %>
    </td>
    <td>
      <div class="invoice-line-controls">
      <div class="field">
      <%= f.label :qty, "Aantal" %> 
      <%= f.text_field :qty, :size=>4 %> 
      </div>

      <div class="field">
      <%= f.label :price, "Prijs" %> 
      <%= f.text_field :price, :size=>8 %> <br/> 
      </div>
      <%= link_to_remove_fields "X", f %>
      </div>
    </td>
    </tr>
  </table>

</div>

app/views/invoices/_invoices.html.erb
<%- model_class = Invoice.new.class -%>
<table id="invoices" class="table table-striped table-hover">
  <thead>
    <tr>
      <!--th><%= model_class.human_attribute_name(:id) %></th-->
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:bedrijf) %></th>
      <th><%= model_class.human_attribute_name(:klant) %></th>
      <th><%= model_class.human_attribute_name(:datum) %></th>
      <th><%= model_class.human_attribute_name(:total) %></th>
      <th><%= model_class.human_attribute_name(:total_inc_vat) %></th>
      <th style="width:16em;"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% invoices.each do |invoice| %>
      <tr>
        <!-- td><%= link_to invoice.id, invoice_path(invoice) %></td -->
        <% if invoice.offerte || invoice.offerte.nil? %>
          <td> <%= link_to "0"+invoice.id.to_s+"_OFFERTE", invoice_path( invoice ) %> </td>
        <% else %>
          <td><%= link_to invoice.number, invoice_path(invoice) %></td>
        <% end %>
        <td><%= link_to invoice.firm.name, firm_path(invoice.firm) %></td>
        <td><%= link_to invoice.client.name, client_path(invoice.client) %></td>
        <td><%= invoice.datum %></td>
        <td><%= to_euro( invoice.total_ex_vat ) %></td>
        <td>
            <% if invoice.no_vat %>
              NO VAT!
            <% else %>
              <%= to_euro( invoice.total ) %></td>
            <% end %>
        <td>
          <div class="btn-group">
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_invoice_path(invoice), :class => 'btn btn-mini' %>

            <%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        invoice_path(invoice),
                        :method => :delete,
                        :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                        :class => 'btn btn-mini btn-danger' %>

            <%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %>


            <%= link_to t('Print PDF', :default => t("helpers.links.printpdf")),
              invoice_path(invoice, :format=>"pdf"), :class => 'btn btn-mini', :target=>'_blank' %>
          </div>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoices/edit.html.erb
<% title "Bewerk "+@invoice.title %>
<h1> <%="Bewerk "+@invoice.title %> </h1>

<%= render 'form', :invoice => @invoice %>

app/views/invoices/index.html.erb
<% title "Facturen en Offertes" %>
<h1>Facturen en offertes</h1>

<%= link_to t('Nieuwe factuur/offerte'),
            new_invoice_path,
            :class => 'btn btn-primary add-button' %>

<%= render 'invoices', :invoices => @invoices %>

app/views/invoices/new.html.erb
<% title "Nieuwe "+@invoice.title %>
<h1>Nieuwe <%=@invoice.title%> </h1>

<%= render 'form', invoice: @invoice %>

app/views/invoices/search.html.erb
Zoek op Factuur nr: 
<%= link_to "Facturen", invoices_path %>

app/views/invoices/show.html.erb
<% if @invoice.offerte %>
  <h1>Offerte <%= @invoice.number %> (<%= @invoice.id %>)</h1>
<% else %>
  <h1>Factuur <%= @invoice.number %></h1>
<% end %>

<% title @invoice.title %>

<p>
  <%= link_to "Print (PDF)", invoice_path(@invoice, :format => "pdf"), :class=>"btn" %> 
</p>

<table width="100%">
<tr>
<td valign="top">
<p>
  <%=h @invoice.firm.name%>
</p>
</td>
<td> &nbsp; &nbsp;</td>
<td>
<p>
  <strong>Klant:</strong>
  <%=h @invoice.client.name %>  <br/>

  <strong>Adres:</strong>
  <%=h @invoice.client.address %> <br/>

  <strong>Phone:</strong>
  <%=h @invoice.client.phone %> <br/>


  <strong>E-mail:</strong>
  <%=h @invoice.client.email %> <br/>

 <strong>VAT:</strong>
  <%=h @invoice.client.vat %> <br/>


</p>
</td>
</tr>
<tr>
<td>
<p>
  <% if @invoice.offerte %>
     <strong>OFFERTE:</strong>
      <%=h @invoice.number %>
      (<%= @invoice.id %>)
  <% else %>
    <strong>FACTUUR:</strong>
    <%=h @invoice.number %>
  <% end %>

  
  <% if @invoice.no_vat %>
    <br/>
    Geen BTW wordt hiervoor aangerekend
  <% end %>
</p>
</td>
</tr>
</table>


<table class="table table-striped">
<thead>
  <tr>
    <th> Beschrijving</th>
    <th> Aantal</th>
    <th> E.P.</th>
    <th> Prijs ex. BTW</th>
  </tr>
</thead>
<tbody>
  <% for item in @invoice.invoice_lines %>
    <tr>
      <td> <%= item.description %> </td>
      <td> <%= item.qty %> </td>
      <td> <%= to_euro(item.price) %> </td>
      <td> <%= to_euro(item.total) %> </td>
    </tr>
  <% end %>

  <%if @invoice.no_vat  %>
    <tr><td></td><td colspan="2">Totaal zonder btw</td><td> <%= to_euro @invoice.total_ex_vat %> </td></tr>
    <tr><td></td><td colspan="3">
      BTW verlegd - BTW te voldoen door medecontractant - 
        art.196 BTW richtlijn 2006/112/EG
    </td></tr>
  <% else %>
    <tr><td></td><td colspan="2">Totaal ex btw</td><td> <%= @invoice.total_ex_vat %> euro </td></tr>
    <tr><td></td><td colspan="2">Totaal</td><td> <%= @invoice.total %> euro </td></tr>
  <% end %>



</tbody>

</table>

<p>
Gelieve 
<% if @invoice.no_vat %>
  <%= to_euro( @invoice.total_ex_vat) %> 
<% else %>
  <%= to_euro( @invoice.total) %> 
<% end %>
over te schrijven op rekening <%= @invoice.firm.bank %> met mededeling 
  <%=h @invoice.mededeling%>
</p>



<p>
  <%= link_to "Edit", edit_invoice_path(@invoice), :class=>"btn" %> 
  <%= link_to 'Destroy', @invoice, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <%= link_to "View All", invoices_path, :class=>"btn" %>
</p>