config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :invoices
  resources :invoice_lines
  resources :firms
  resources :clients
  # match ':controller(/:action(/:id))(.:format)'

  root to: 'invoices#index'
end

app/models/invoice_line.rb
# frozen_string_literal: true

# Author: Walter Schreppers
# Description:
#   Stores seperate lines for each invoice in db
class InvoiceLine < ActiveRecord::Base
  # TODO: add param filtering (search box)
  # attr_accessible :description, :qty, :price

  belongs_to :invoice

  def total
    if qty.nil?
      price
    else
      price * qty
    end
  end
end

app/controllers/invoice_lines_controller.rb
# frozen_string_literal: true

# Author: Walter Schreppers
# Description:
#   Invoice lines (every invoice has 1-n lines where you state tarif + qty)
#
class InvoiceLinesController < ApplicationController
  # GET /invoice_lines
  # GET /invoice_lines.json
  def index
    @invoice_lines = InvoiceLine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoice_lines }
    end
  end

  # GET /invoice_lines/1
  # GET /invoice_lines/1.json
  def show
    @invoice_line = InvoiceLine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoice_line }
    end
  end

  # GET /invoice_lines/new
  # GET /invoice_lines/new.json
  def new
    @invoice_line = InvoiceLine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoice_line }
    end
  end

  # GET /invoice_lines/1/edit
  def edit
    @invoice_line = InvoiceLine.find(params[:id])
  end

  # POST /invoice_lines
  # POST /invoice_lines.json
  def create
    @invoice_line = InvoiceLine.new(params[:invoice_line])

    respond_to do |format|
      if @invoice_line.save
        format.html { redirect_to @invoice_line, notice: 'Invoice line was successfully created.' }
        format.json { render json: @invoice_line, status: :created, location: @invoice_line }
      else
        format.html { render action: 'new' }
        format.json { render json: @invoice_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invoice_lines/1
  # PUT /invoice_lines/1.json
  def update
    @invoice_line = InvoiceLine.find(params[:id])

    respond_to do |format|
      if @invoice_line.update_attributes(params[:invoice_line])
        format.html { redirect_to @invoice_line, notice: 'Invoice line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invoice_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_lines/1
  # DELETE /invoice_lines/1.json
  def destroy
    @invoice_line = InvoiceLine.find(params[:id])
    @invoice_line.destroy

    respond_to do |format|
      format.html { redirect_to invoice_lines_url }
      format.json { head :no_content }
    end
  end
end

app/views/invoice_lines/_form.html.erb
<%= form_for @invoice_line, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :invoice_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :invoice_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :qty, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :qty, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :price, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                invoice_lines_path, :class => 'btn' %>
  </div>
<% end %>

app/views/invoice_lines/edit.html.erb
<%- model_class = @invoice_line.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/invoice_lines/index.html.erb
<%- model_class = InvoiceLine.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:invoice_id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:qty) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @invoice_lines.each do |invoice_line| %>
      <tr>
        <td><%= link_to invoice_line.id, invoice_line_path(invoice_line) %></td>
        <td><%= invoice_line.invoice_id %></td>
        <td><%= invoice_line.description %></td>
        <td><%= invoice_line.qty %></td>
        <td><%= invoice_line.price %></td>
        <td><%=l invoice_line.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_invoice_line_path(invoice_line), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      invoice_line_path(invoice_line),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_invoice_line_path,
            :class => 'btn btn-primary' %>

app/views/invoice_lines/new.html.erb
<%- model_class = @invoice_line.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/invoice_lines/show.html.erb
<%- model_class = @invoice_line.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:invoice_id) %>:</strong></dt>
  <dd><%= @invoice_line.invoice_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @invoice_line.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:qty) %>:</strong></dt>
  <dd><%= @invoice_line.qty %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @invoice_line.price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              invoice_lines_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_invoice_line_path(@invoice_line), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              invoice_line_path(@invoice_line),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>