config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :invoices
  resources :invoice_lines
  resources :firms
  resources :clients
  # match ':controller(/:action(/:id))(.:format)'

  root to: 'invoices#index'
end

app/views/layouts/navigation/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    Written in Ruby on Rails 
  </div>
  <strong>
    Copyright © <%= DateTime.now.year %>
    <a href="http://www.sitweb.eu"> SIT bvba</a>
  </strong>
  All rights reserved.
</footer>

app/views/layouts/navigation/_header.html.erb
<header class="main-header">

  <%= link_to "SIT & AnyKey facturen", root_path, :class=>"logo" %> 

  <nav class="navbar navbar-static-top" role="navigation">
    <div class="navbar-custom-menu">
    </div>
  </nav>

</header>

app/views/layouts/navigation/_layout.erb
<%= render "layouts/navigation/header" %>
<%= render "layouts/navigation/sidebar" %>

app/views/layouts/navigation/_sidebar.html.erb
<div class="main-sidebar">
  <div class="sidebar">
    
    <form action="#" class="sidebar-form" method="get">
      <div class="input-group">
        <input class="form-control" name="q" placeholder="Search..." type="text" />
        <span class="input-group-btn">
        <button class="btn btn-flat" id="search-btn" name="search" type="submit">
        <i class="fa fa-search">
        </i></button></span>
      </div>
    </form>
    <ul class="sidebar-menu">
      <li class="header">
        Menu
      </li>

      <li><%= link_to "Facturen", invoices_path %></li>
      <li><%= link_to "Klanten",  clients_path %></li>
      <li><%= link_to "Bedrijven", firms_path %></li>

      <!-- treeview js is not used 
      <li class="treeview">
        <a href="#">
          <span>Multilevel</span>
          <i class="fa fa-angle-left pull-right">
          </i></a>
        <ul class="treeview-menu">
          <li>
            <a href="#"> Link in level 2</a>
          </li>
          <li>
            <a href="#"> Link in level 2</a>
          </li>
        </ul>
        </li>
      -->

    </ul>
  </div>
</div>